apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: dind-test
spec:
  entrypoint: entrypoint
  arguments:
    parameters:
      - name: name
        value: "world"
  templates:
    - name: entrypoint
      steps: 
      - - name: hello
          template: hello
          arguments:
            parameters: 
              - name: name
                value: "{{workflow.parameters.name}}"
      - - name: dind-sidecar
          template: dind-sidecar
    - name: hello
      inputs:
        parameters:
          - name: name
      container:
        image: docker/whalesay
        command:
          - cowsay
        args:
          - "Hello {{inputs.parameters.name}}"
    - name: dind-sidecar
      script:
        image: docker:19.03.13
        command: [sh]
        source: |
          set -euo pipefail
          until docker ps >/dev/null; do sleep 3; done
          docker run --rm debian:latest
          cat /etc/os-release
        env:
        - name: DOCKER_HOST               # the docker daemon can be access on the standard port on localhost
          value: 127.0.0.1
      sidecars:
      - name: dind
        image: docker:19.03.13-dind          # Docker already provides an image for running a Docker daemon
        env:
          - name: DOCKER_TLS_CERTDIR         # Docker TLS env config
            value: ""
        securityContext:
          privileged: true                # the Docker daemon can only run in a privileged container
        # mirrorVolumeMounts will mount the same volumes specified in the main container
        # to the sidecar (including artifacts), at the same mountPaths. This enables
        # dind daemon to (partially) see the same filesystem as the main container in
        # order to use features such as docker volume binding.
        mirrorVolumeMounts: true
